### ISSUE TITLE
Name selection must be deterministic in order to actually test the tool

### ISSUE THREAD

**Issue by ande2101** [grayleonard/booxtream-epub-drm-remover#1]
The only way to test whether a book has been correctly deloused is if two different inputs produce the same output. Having random names in there removes the ability for a user to perform this check, thus making the script vulnerable to more subtle watermarking schemes in the future.

So the `random` module has to go.

**Comment by grayleonard** [comment]
Yes, you are right. Commit e630fff adds deterministic file naming, which I have just pushed to master. 

I found that built zip files have different checksums because of header differences (modification date, filename, etc) - I have included [diff.sh](https://github.com/grayleonard/booxtream-epub-drm-remover/blob/master/diff.sh) to compare two zip files by extracting their contents and diffing each extracted file.
